{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "def216a3-dc7c-441e-94ec-9a90233d11f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model loaded successfully from models/asl_resnet_model.pth\n",
      "Starting ASL Detection Server...\n",
      "Open http://localhost:5000 in your browser\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on all addresses (0.0.0.0)\n",
      " * Running on http://127.0.0.1:5000\n",
      " * Running on http://192.168.43.87:5000\n",
      "Press CTRL+C to quit\n",
      " * Restarting with stat\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "1",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 1\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, request, jsonify, render_template_string\n",
    "from flask_cors import CORS\n",
    "import cv2\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torchvision import transforms, models\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "import base64\n",
    "import io\n",
    "import json\n",
    "import time\n",
    "from collections import deque, Counter\n",
    "import os\n",
    "\n",
    "app = Flask(__name__)\n",
    "CORS(app)\n",
    "\n",
    "# ASL Classes\n",
    "ASL_CLASSES = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',\n",
    "               'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',\n",
    "               'U', 'V', 'W', 'X', 'Y', 'Z', 'del', 'nothing', 'space']\n",
    "\n",
    "class FingerSpellingEngine:\n",
    "    def __init__(self):\n",
    "        self.current_word = \"\"\n",
    "        self.sentence = \"\"\n",
    "        self.word_history = []\n",
    "        self.last_prediction = \"\"\n",
    "        self.last_prediction_time = 0\n",
    "        self.prediction_hold_time = 1.5  # seconds\n",
    "        self.delete_hold_time = 2.0\n",
    "        self.space_hold_time = 1.0\n",
    "        \n",
    "        # Common words for suggestions\n",
    "        self.common_words = set([\n",
    "            'hello', 'world', 'how', 'are', 'you', 'what', 'when', 'where',\n",
    "            'why', 'who', 'good', 'bad', 'yes', 'no', 'please', 'thank',\n",
    "            'sorry', 'help', 'love', 'like', 'want', 'need', 'time', 'day',\n",
    "            'night', 'morning', 'afternoon', 'evening', 'food', 'water',\n",
    "            'home', 'work', 'school', 'friend', 'family', 'happy', 'sad',\n",
    "            'the', 'and', 'for', 'with', 'this', 'that', 'have', 'will',\n",
    "            'can', 'could', 'should', 'would', 'make', 'take', 'give',\n",
    "            'get', 'go', 'come', 'see', 'know', 'think', 'feel', 'look'\n",
    "        ])\n",
    "        \n",
    "        # Prediction smoothing\n",
    "        self.prediction_buffer = deque(maxlen=10)\n",
    "        self.confidence_threshold = 0.75\n",
    "        \n",
    "    def smooth_prediction(self, predicted_class, confidence):\n",
    "        \"\"\"Smooth predictions using a buffer\"\"\"\n",
    "        self.prediction_buffer.append((predicted_class, confidence))\n",
    "        \n",
    "        # Only consider high confidence predictions\n",
    "        high_conf_predictions = [pred for pred, conf in self.prediction_buffer if conf > self.confidence_threshold]\n",
    "        \n",
    "        if len(high_conf_predictions) < 3:  # Need at least 3 consistent predictions\n",
    "            return None, 0\n",
    "        \n",
    "        # Get most common prediction\n",
    "        counter = Counter(high_conf_predictions)\n",
    "        most_common_pred, count = counter.most_common(1)[0]\n",
    "        \n",
    "        # Calculate average confidence for the most common prediction\n",
    "        avg_confidence = np.mean([conf for pred, conf in self.prediction_buffer if pred == most_common_pred])\n",
    "        \n",
    "        return most_common_pred, avg_confidence\n",
    "    \n",
    "    def process_prediction(self, predicted_class, confidence):\n",
    "        \"\"\"Process the prediction and update word/sentence\"\"\"\n",
    "        current_time = time.time()\n",
    "        \n",
    "        # Smooth the prediction\n",
    "        smoothed_pred, smoothed_conf = self.smooth_prediction(predicted_class, confidence)\n",
    "        \n",
    "        if smoothed_pred is None:\n",
    "            return False\n",
    "        \n",
    "        # Check if prediction has been held long enough\n",
    "        if smoothed_pred == self.last_prediction:\n",
    "            hold_time = current_time - self.last_prediction_time\n",
    "            \n",
    "            if smoothed_pred == 'del' and hold_time > self.delete_hold_time:\n",
    "                self.handle_delete()\n",
    "                self.last_prediction_time = current_time\n",
    "                return True\n",
    "                \n",
    "            elif smoothed_pred == 'space' and hold_time > self.space_hold_time:\n",
    "                self.handle_space()\n",
    "                self.last_prediction_time = current_time\n",
    "                return True\n",
    "                \n",
    "            elif smoothed_pred not in ['del', 'space', 'nothing'] and hold_time > self.prediction_hold_time:\n",
    "                self.add_letter(smoothed_pred)\n",
    "                self.last_prediction_time = current_time\n",
    "                return True\n",
    "        else:\n",
    "            # New prediction\n",
    "            self.last_prediction = smoothed_pred\n",
    "            self.last_prediction_time = current_time\n",
    "            \n",
    "        return False\n",
    "    \n",
    "    def add_letter(self, letter):\n",
    "        \"\"\"Add letter to current word\"\"\"\n",
    "        if letter not in ['del', 'space', 'nothing']:\n",
    "            self.current_word += letter.lower()\n",
    "    \n",
    "    def handle_delete(self):\n",
    "        \"\"\"Handle delete action\"\"\"\n",
    "        if self.current_word:\n",
    "            self.current_word = self.current_word[:-1]\n",
    "        elif self.sentence:\n",
    "            self.sentence = self.sentence[:-1]\n",
    "    \n",
    "    def handle_space(self):\n",
    "        \"\"\"Handle space action - finalize word and add to sentence\"\"\"\n",
    "        if self.current_word:\n",
    "            self.word_history.append(self.current_word)\n",
    "            \n",
    "            if self.sentence:\n",
    "                self.sentence += \" \" + self.current_word\n",
    "            else:\n",
    "                self.sentence = self.current_word\n",
    "            \n",
    "            self.current_word = \"\"\n",
    "    \n",
    "    def get_word_suggestions(self):\n",
    "        \"\"\"Get word suggestions based on current partial word\"\"\"\n",
    "        if len(self.current_word) < 2:\n",
    "            return []\n",
    "        \n",
    "        suggestions = []\n",
    "        for word in self.common_words:\n",
    "            if word.startswith(self.current_word.lower()):\n",
    "                suggestions.append(word)\n",
    "        \n",
    "        return sorted(suggestions)[:3]\n",
    "    \n",
    "    def get_status(self):\n",
    "        \"\"\"Get current status for display\"\"\"\n",
    "        return {\n",
    "            'current_word': self.current_word,\n",
    "            'sentence': self.sentence,\n",
    "            'suggestions': self.get_word_suggestions(),\n",
    "            'last_prediction': self.last_prediction,\n",
    "            'word_count': len(self.word_history)\n",
    "        }\n",
    "    \n",
    "    def clear_all(self):\n",
    "        \"\"\"Clear everything\"\"\"\n",
    "        self.current_word = \"\"\n",
    "        self.sentence = \"\"\n",
    "        self.word_history = []\n",
    "    \n",
    "    def undo_last_word(self):\n",
    "        \"\"\"Undo last word\"\"\"\n",
    "        if self.word_history:\n",
    "            removed_word = self.word_history.pop()\n",
    "            self.sentence = \" \".join(self.word_history)\n",
    "\n",
    "def create_resnet_model(num_classes):\n",
    "    \"\"\"Create ResNet18 model\"\"\"\n",
    "    model = models.resnet18(pretrained=False)\n",
    "    model.fc = nn.Linear(model.fc.in_features, num_classes)\n",
    "    return model\n",
    "\n",
    "def load_model(model_path, model_type='resnet'):\n",
    "    \"\"\"Load the appropriate model\"\"\"\n",
    "    try:\n",
    "        if model_type == 'resnet':\n",
    "            model = create_resnet_model(len(ASL_CLASSES))\n",
    "            model.load_state_dict(torch.load(model_path, map_location='cpu'))\n",
    "            model.eval()\n",
    "            return model\n",
    "        # Add other model types here (GNN, ViT) as needed\n",
    "    except Exception as e:\n",
    "        print(f\"Error loading model: {e}\")\n",
    "        return None\n",
    "\n",
    "def preprocess_image(image_data, image_size=224):\n",
    "    \"\"\"Preprocess image for model inference\"\"\"\n",
    "    try:\n",
    "        # Decode base64 image\n",
    "        image_bytes = base64.b64decode(image_data.split(',')[1])\n",
    "        image = Image.open(io.BytesIO(image_bytes))\n",
    "        \n",
    "        # Convert to RGB if needed\n",
    "        if image.mode != 'RGB':\n",
    "            image = image.convert('RGB')\n",
    "        \n",
    "        # Apply transforms\n",
    "        transform = transforms.Compose([\n",
    "            transforms.Resize((image_size, image_size)),\n",
    "            transforms.ToTensor(),\n",
    "            transforms.Normalize(mean=[0.485, 0.456, 0.406],\n",
    "                               std=[0.229, 0.224, 0.225])\n",
    "        ])\n",
    "        \n",
    "        tensor = transform(image).unsqueeze(0)\n",
    "        return tensor\n",
    "    except Exception as e:\n",
    "        print(f\"Error preprocessing image: {e}\")\n",
    "        return None\n",
    "\n",
    "# Global variables\n",
    "model = None\n",
    "spelling_engine = FingerSpellingEngine()\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    \"\"\"Serve the main HTML page\"\"\"\n",
    "    html_template = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"en\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "    <title>ASL Real-Time Detection</title>\n",
    "    <style>\n",
    "        * {\n",
    "            margin: 0;\n",
    "            padding: 0;\n",
    "            box-sizing: border-box;\n",
    "        }\n",
    "\n",
    "        body {\n",
    "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n",
    "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n",
    "            min-height: 100vh;\n",
    "            color: white;\n",
    "            overflow-x: hidden;\n",
    "        }\n",
    "\n",
    "        .container {\n",
    "            max-width: 1400px;\n",
    "            margin: 0 auto;\n",
    "            padding: 20px;\n",
    "        }\n",
    "\n",
    "        .header {\n",
    "            text-align: center;\n",
    "            margin-bottom: 30px;\n",
    "            animation: fadeInDown 1s ease-out;\n",
    "        }\n",
    "\n",
    "        .header h1 {\n",
    "            font-size: 3rem;\n",
    "            font-weight: 700;\n",
    "            margin-bottom: 10px;\n",
    "            background: linear-gradient(45deg, #00f2fe, #4facfe);\n",
    "            -webkit-background-clip: text;\n",
    "            -webkit-text-fill-color: transparent;\n",
    "            background-clip: text;\n",
    "        }\n",
    "\n",
    "        .main-content {\n",
    "            display: grid;\n",
    "            grid-template-columns: 2fr 1fr;\n",
    "            gap: 30px;\n",
    "            margin-bottom: 30px;\n",
    "        }\n",
    "\n",
    "        .video-section {\n",
    "            background: rgba(255, 255, 255, 0.1);\n",
    "            backdrop-filter: blur(10px);\n",
    "            border-radius: 20px;\n",
    "            padding: 25px;\n",
    "            border: 1px solid rgba(255, 255, 255, 0.2);\n",
    "        }\n",
    "\n",
    "        #videoElement {\n",
    "            width: 100%;\n",
    "            height: 400px;\n",
    "            object-fit: cover;\n",
    "            border-radius: 15px;\n",
    "            border: 3px solid rgba(255, 255, 255, 0.3);\n",
    "        }\n",
    "\n",
    "        .roi-overlay {\n",
    "            position: absolute;\n",
    "            top: 50%;\n",
    "            left: 50%;\n",
    "            transform: translate(-50%, -60%);\n",
    "            width: 250px;\n",
    "            height: 250px;\n",
    "            border: 3px solid #00ff88;\n",
    "            border-radius: 15px;\n",
    "            box-shadow: 0 0 20px rgba(0, 255, 136, 0.5);\n",
    "        }\n",
    "\n",
    "        .controls {\n",
    "            display: flex;\n",
    "            gap: 15px;\n",
    "            justify-content: center;\n",
    "            flex-wrap: wrap;\n",
    "            margin-top: 20px;\n",
    "        }\n",
    "\n",
    "        .btn {\n",
    "            padding: 12px 24px;\n",
    "            border: none;\n",
    "            border-radius: 25px;\n",
    "            font-size: 14px;\n",
    "            font-weight: 600;\n",
    "            cursor: pointer;\n",
    "            transition: all 0.3s ease;\n",
    "        }\n",
    "\n",
    "        .btn-primary {\n",
    "            background: linear-gradient(45deg, #00ff88, #00d4aa);\n",
    "            color: white;\n",
    "        }\n",
    "\n",
    "        .btn-secondary {\n",
    "            background: rgba(255, 255, 255, 0.2);\n",
    "            color: white;\n",
    "            border: 1px solid rgba(255, 255, 255, 0.3);\n",
    "        }\n",
    "\n",
    "        .info-panel {\n",
    "            background: rgba(255, 255, 255, 0.1);\n",
    "            backdrop-filter: blur(10px);\n",
    "            border-radius: 20px;\n",
    "            padding: 25px;\n",
    "            border: 1px solid rgba(255, 255, 255, 0.2);\n",
    "        }\n",
    "\n",
    "        .prediction-display {\n",
    "            text-align: center;\n",
    "            margin-bottom: 30px;\n",
    "            padding: 20px;\n",
    "            background: rgba(0, 0, 0, 0.3);\n",
    "            border-radius: 15px;\n",
    "        }\n",
    "\n",
    "        .current-sign {\n",
    "            font-size: 3rem;\n",
    "            font-weight: bold;\n",
    "            color: #00ff88;\n",
    "            margin-bottom: 10px;\n",
    "        }\n",
    "\n",
    "        .spelling-section {\n",
    "            background: rgba(255, 255, 255, 0.1);\n",
    "            backdrop-filter: blur(10px);\n",
    "            border-radius: 20px;\n",
    "            padding: 25px;\n",
    "            border: 1px solid rgba(255, 255, 255, 0.2);\n",
    "        }\n",
    "\n",
    "        .word-display {\n",
    "            font-size: 1.5rem;\n",
    "            font-weight: bold;\n",
    "            color: #ffeb3b;\n",
    "            padding: 15px;\n",
    "            background: rgba(0, 0, 0, 0.4);\n",
    "            border-radius: 10px;\n",
    "            margin-bottom: 20px;\n",
    "        }\n",
    "\n",
    "        .sentence-display {\n",
    "            background: rgba(0, 0, 0, 0.4);\n",
    "            padding: 20px;\n",
    "            border-radius: 10px;\n",
    "            min-height: 120px;\n",
    "            font-size: 1.1rem;\n",
    "            line-height: 1.6;\n",
    "        }\n",
    "\n",
    "        .status-indicator {\n",
    "            position: fixed;\n",
    "            top: 20px;\n",
    "            right: 20px;\n",
    "            padding: 10px 15px;\n",
    "            border-radius: 20px;\n",
    "            font-weight: bold;\n",
    "        }\n",
    "\n",
    "        .status-active { background: linear-gradient(45deg, #00ff88, #00d4aa); }\n",
    "        .status-inactive { background: rgba(255, 255, 255, 0.2); }\n",
    "\n",
    "        @keyframes fadeInDown {\n",
    "            from { opacity: 0; transform: translateY(-30px); }\n",
    "            to { opacity: 1; transform: translateY(0); }\n",
    "        }\n",
    "\n",
    "        @media (max-width: 1200px) {\n",
    "            .main-content { grid-template-columns: 1fr; }\n",
    "        }\n",
    "\n",
    "        #canvas { display: none; }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "    <div class=\"container\">\n",
    "        <div class=\"header\">\n",
    "            <h1>ASL Real-Time Detection</h1>\n",
    "            <p>AI-powered finger spelling recognition</p>\n",
    "        </div>\n",
    "\n",
    "        <div class=\"status-indicator\" id=\"statusIndicator\">Camera Inactive</div>\n",
    "\n",
    "        <div class=\"main-content\">\n",
    "            <div class=\"video-section\">\n",
    "                <div style=\"position: relative;\">\n",
    "                    <video id=\"videoElement\" autoplay muted playsinline></video>\n",
    "                    <div class=\"roi-overlay\"></div>\n",
    "                </div>\n",
    "                \n",
    "                <div class=\"controls\">\n",
    "                    <button class=\"btn btn-primary\" id=\"startBtn\">Start Detection</button>\n",
    "                    <button class=\"btn btn-secondary\" id=\"stopBtn\">Stop Detection</button>\n",
    "                    <button class=\"btn btn-secondary\" id=\"clearBtn\">Clear All</button>\n",
    "                    <button class=\"btn btn-secondary\" id=\"undoBtn\">Undo Word</button>\n",
    "                </div>\n",
    "            </div>\n",
    "\n",
    "            <div class=\"info-panel\">\n",
    "                <div class=\"prediction-display\">\n",
    "                    <div class=\"current-sign\" id=\"currentSign\">-</div>\n",
    "                    <div>Confidence: <span id=\"confidenceValue\">0%</span></div>\n",
    "                </div>\n",
    "\n",
    "                <div style=\"text-align: center; margin-bottom: 20px;\">\n",
    "                    <div style=\"font-size: 1.2rem; margin-bottom: 10px;\">FPS: <span id=\"fpsValue\">0</span></div>\n",
    "                    <div>Words: <span id=\"wordCount\">0</span></div>\n",
    "                </div>\n",
    "            </div>\n",
    "        </div>\n",
    "\n",
    "        <div class=\"spelling-section\">\n",
    "            <h3 style=\"margin-bottom: 20px;\">Finger Spelling</h3>\n",
    "            \n",
    "            <div>\n",
    "                <label>Current Word:</label>\n",
    "                <div class=\"word-display\" id=\"currentWord\">_</div>\n",
    "            </div>\n",
    "\n",
    "            <div>\n",
    "                <label>Complete Sentence:</label>\n",
    "                <div class=\"sentence-display\" id=\"sentenceText\">Start spelling to see your sentence here...</div>\n",
    "            </div>\n",
    "        </div>\n",
    "    </div>\n",
    "\n",
    "    <canvas id=\"canvas\"></canvas>\n",
    "\n",
    "    <script>\n",
    "        class ASLApp {\n",
    "            constructor() {\n",
    "                this.isDetecting = false;\n",
    "                this.video = document.getElementById('videoElement');\n",
    "                this.canvas = document.getElementById('canvas');\n",
    "                this.ctx = this.canvas.getContext('2d');\n",
    "                this.fps = 0;\n",
    "                this.frameCount = 0;\n",
    "                this.lastTime = Date.now();\n",
    "                \n",
    "                this.initElements();\n",
    "                this.bindEvents();\n",
    "            }\n",
    "\n",
    "            initElements() {\n",
    "                this.elements = {\n",
    "                    startBtn: document.getElementById('startBtn'),\n",
    "                    stopBtn: document.getElementById('stopBtn'),\n",
    "                    clearBtn: document.getElementById('clearBtn'),\n",
    "                    undoBtn: document.getElementById('undoBtn'),\n",
    "                    statusIndicator: document.getElementById('statusIndicator'),\n",
    "                    currentSign: document.getElementById('currentSign'),\n",
    "                    confidenceValue: document.getElementById('confidenceValue'),\n",
    "                    fpsValue: document.getElementById('fpsValue'),\n",
    "                    wordCount: document.getElementById('wordCount'),\n",
    "                    currentWord: document.getElementById('currentWord'),\n",
    "                    sentenceText: document.getElementById('sentenceText')\n",
    "                };\n",
    "            }\n",
    "\n",
    "            bindEvents() {\n",
    "                this.elements.startBtn.onclick = () => this.startDetection();\n",
    "                this.elements.stopBtn.onclick = () => this.stopDetection();\n",
    "                this.elements.clearBtn.onclick = () => this.clearAll();\n",
    "                this.elements.undoBtn.onclick = () => this.undoWord();\n",
    "            }\n",
    "\n",
    "            async startDetection() {\n",
    "                try {\n",
    "                    const stream = await navigator.mediaDevices.getUserMedia({\n",
    "                        video: { width: 1280, height: 720, facingMode: 'user' }\n",
    "                    });\n",
    "                    \n",
    "                    this.video.srcObject = stream;\n",
    "                    this.isDetecting = true;\n",
    "                    \n",
    "                    this.elements.statusIndicator.textContent = 'Camera Active';\n",
    "                    this.elements.statusIndicator.className = 'status-indicator status-active';\n",
    "                    \n",
    "                    this.elements.startBtn.disabled = true;\n",
    "                    this.elements.stopBtn.disabled = false;\n",
    "                    \n",
    "                    this.startProcessing();\n",
    "                } catch (error) {\n",
    "                    alert('Could not access camera: ' + error.message);\n",
    "                }\n",
    "            }\n",
    "\n",
    "            stopDetection() {\n",
    "                if (this.video.srcObject) {\n",
    "                    this.video.srcObject.getTracks().forEach(track => track.stop());\n",
    "                    this.video.srcObject = null;\n",
    "                }\n",
    "                \n",
    "                this.isDetecting = false;\n",
    "                this.elements.statusIndicator.textContent = 'Camera Inactive';\n",
    "                this.elements.statusIndicator.className = 'status-indicator status-inactive';\n",
    "                \n",
    "                this.elements.startBtn.disabled = false;\n",
    "                this.elements.stopBtn.disabled = true;\n",
    "            }\n",
    "\n",
    "            startProcessing() {\n",
    "                const process = async () => {\n",
    "                    if (!this.isDetecting) return;\n",
    "                    \n",
    "                    this.captureFrame();\n",
    "                    this.updateFPS();\n",
    "                    \n",
    "                    setTimeout(process, 100); // 10 FPS\n",
    "                };\n",
    "                process();\n",
    "            }\n",
    "\n",
    "            captureFrame() {\n",
    "                if (this.video.videoWidth === 0) return;\n",
    "                \n",
    "                // Set canvas size to match video\n",
    "                this.canvas.width = this.video.videoWidth;\n",
    "                this.canvas.height = this.video.videoHeight;\n",
    "                \n",
    "                // Draw video frame to canvas\n",
    "                this.ctx.drawImage(this.video, 0, 0);\n",
    "                \n",
    "                // Extract ROI (center region)\n",
    "                const roiSize = 300;\n",
    "                const x = (this.canvas.width - roiSize) / 2;\n",
    "                const y = (this.canvas.height - roiSize) / 2 - 50;\n",
    "                \n",
    "                const imageData = this.ctx.getImageData(x, y, roiSize, roiSize);\n",
    "                const canvas = document.createElement('canvas');\n",
    "                canvas.width = roiSize;\n",
    "                canvas.height = roiSize;\n",
    "                const ctx = canvas.getContext('2d');\n",
    "                ctx.putImageData(imageData, 0, 0);\n",
    "                \n",
    "                // Convert to base64\n",
    "                const dataURL = canvas.toDataURL('image/jpeg', 0.8);\n",
    "                \n",
    "                // Send to server\n",
    "                this.sendFrameToServer(dataURL);\n",
    "            }\n",
    "\n",
    "            async sendFrameToServer(imageData) {\n",
    "                try {\n",
    "                    const response = await fetch('/predict', {\n",
    "                        method: 'POST',\n",
    "                        headers: { 'Content-Type': 'application/json' },\n",
    "                        body: JSON.stringify({ image: imageData })\n",
    "                    });\n",
    "                    \n",
    "                    const result = await response.json();\n",
    "                    this.updateUI(result);\n",
    "                } catch (error) {\n",
    "                    console.error('Prediction error:', error);\n",
    "                }\n",
    "            }\n",
    "\n",
    "            updateUI(result) {\n",
    "                if (result.error) {\n",
    "                    console.error('Server error:', result.error);\n",
    "                    return;\n",
    "                }\n",
    "                \n",
    "                this.elements.currentSign.textContent = result.predicted_class || '-';\n",
    "                this.elements.confidenceValue.textContent = \n",
    "                    result.confidence ? `${(result.confidence * 100).toFixed(1)}%` : '0%';\n",
    "                \n",
    "                if (result.spelling_status) {\n",
    "                    const status = result.spelling_status;\n",
    "                    this.elements.currentWord.textContent = status.current_word + '_';\n",
    "                    this.elements.sentenceText.textContent = \n",
    "                        status.sentence || 'Start spelling to see your sentence here...';\n",
    "                    this.elements.wordCount.textContent = status.word_count;\n",
    "                }\n",
    "            }\n",
    "\n",
    "            updateFPS() {\n",
    "                this.frameCount++;\n",
    "                const now = Date.now();\n",
    "                if (now - this.lastTime >= 1000) {\n",
    "                    this.fps = this.frameCount;\n",
    "                    this.elements.fpsValue.textContent = this.fps;\n",
    "                    this.frameCount = 0;\n",
    "                    this.lastTime = now;\n",
    "                }\n",
    "            }\n",
    "\n",
    "            async clearAll() {\n",
    "                await fetch('/clear', { method: 'POST' });\n",
    "                this.elements.currentWord.textContent = '_';\n",
    "                this.elements.sentenceText.textContent = 'Start spelling to see your sentence here...';\n",
    "                this.elements.wordCount.textContent = '0';\n",
    "            }\n",
    "\n",
    "            async undoWord() {\n",
    "                await fetch('/undo', { method: 'POST' });\n",
    "            }\n",
    "        }\n",
    "\n",
    "        const app = new ASLApp();\n",
    "    </script>\n",
    "</body>\n",
    "</html>\n",
    "    \"\"\"\n",
    "    return render_template_string(html_template)\n",
    "\n",
    "@app.route('/predict', methods=['POST'])\n",
    "def predict():\n",
    "    \"\"\"Handle prediction requests\"\"\"\n",
    "    try:\n",
    "        data = request.json\n",
    "        image_data = data.get('image')\n",
    "        \n",
    "        if not image_data:\n",
    "            return jsonify({'error': 'No image data provided'})\n",
    "        \n",
    "        # Preprocess image\n",
    "        tensor = preprocess_image(image_data)\n",
    "        if tensor is None:\n",
    "            return jsonify({'error': 'Failed to process image'})\n",
    "        \n",
    "        # Make prediction\n",
    "        if model is None:\n",
    "            return jsonify({'error': 'Model not loaded'})\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            outputs = model(tensor)\n",
    "            probabilities = torch.softmax(outputs, dim=1)\n",
    "            confidence, predicted = torch.max(probabilities, 1)\n",
    "            \n",
    "            predicted_class = ASL_CLASSES[predicted.item()]\n",
    "            confidence_score = confidence.item()\n",
    "        \n",
    "        # Process with spelling engine\n",
    "        action_taken = spelling_engine.process_prediction(predicted_class, confidence_score)\n",
    "        \n",
    "        return jsonify({\n",
    "            'predicted_class': predicted_class,\n",
    "            'confidence': confidence_score,\n",
    "            'spelling_status': spelling_engine.get_status(),\n",
    "            'action_taken': action_taken\n",
    "        })\n",
    "        \n",
    "    except Exception as e:\n",
    "        return jsonify({'error': str(e)})\n",
    "\n",
    "@app.route('/clear', methods=['POST'])\n",
    "def clear_all():\n",
    "    \"\"\"Clear all text\"\"\"\n",
    "    spelling_engine.clear_all()\n",
    "    return jsonify({'status': 'cleared'})\n",
    "\n",
    "@app.route('/undo', methods=['POST'])\n",
    "def undo_word():\n",
    "    \"\"\"Undo last word\"\"\"\n",
    "    spelling_engine.undo_last_word()\n",
    "    return jsonify({'status': 'undone'})\n",
    "\n",
    "@app.route('/status', methods=['GET'])\n",
    "def get_status():\n",
    "    \"\"\"Get current spelling status\"\"\"\n",
    "    return jsonify(spelling_engine.get_status())\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    # Try to load model\n",
    "    model_paths = [\n",
    "        'models/asl_resnet_model.pth',\n",
    "        'asl_resnet_model.pth',\n",
    "        '../models/asl_resnet_model.pth'\n",
    "    ]\n",
    "    \n",
    "    for path in model_paths:\n",
    "        if os.path.exists(path):\n",
    "            model = load_model(path, 'resnet')\n",
    "            if model:\n",
    "                print(f\"Model loaded successfully from {path}\")\n",
    "                break\n",
    "    \n",
    "    if model is None:\n",
    "        print(\"Warning: Could not load model. Please ensure model file exists.\")\n",
    "        print(\"Expected locations:\", model_paths)\n",
    "    \n",
    "    print(\"Starting ASL Detection Server...\")\n",
    "    print(\"Open http://localhost:5000 in your browser\")\n",
    "    app.run(debug=True, host='0.0.0.0', port=5000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "cebf6c74-458a-4b94-858c-0239baf4daf3",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (1748183370.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[6], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    python asl_app.py\u001b[0m\n\u001b[1;37m           ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "python asl_app.py\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
