{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "def216a3-dc7c-441e-94ec-9a90233d11f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn.functional as F\n",
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "# ========== Define the model architectures you used for training ==========\n",
    "\n",
    "class ResNetASL(torch.nn.Module):\n",
    "    def __init__(self, num_classes):\n",
    "        super().__init__()\n",
    "        from torchvision.models import resnet18\n",
    "        self.model = resnet18(pretrained=False)\n",
    "        self.model.fc = torch.nn.Linear(self.model.fc.in_features, num_classes)\n",
    "    def forward(self, x):\n",
    "        return self.model(x)\n",
    "\n",
    "class GNNASL(torch.nn.Module):\n",
    "    def __init__(self, num_classes):\n",
    "        super().__init__()\n",
    "        # Replace this code with your actual GNN architecture\n",
    "        pass\n",
    "    def forward(self, x):\n",
    "        # Replace with your actual forward logic\n",
    "        return x\n",
    "\n",
    "class ViTASL(torch.nn.Module):\n",
    "    def __init__(self, num_classes):\n",
    "        super().__init__()\n",
    "        # Replace this code with your actual ViT architecture\n",
    "        pass\n",
    "    def forward(self, x):\n",
    "        # Replace with your actual forward logic\n",
    "        return x\n",
    "\n",
    "# ========== Initialize and Load Models ==========\n",
    "\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "num_classes = 26  # A-Z fingerspelling, modify as needed\n",
    "\n",
    "resnet_model = ResNetASL(num_classes).to(device)\n",
    "resnet_model.load_state_dict(torch.load(\"models/asl_resnet_model.pth\", map_location=device))\n",
    "resnet_model.eval()\n",
    "\n",
    "gnn_model = GNNASL(num_classes).to(device)\n",
    "gnn_model.load_state_dict(torch.load(\"models/fast_asl_gnn_final.pth\", map_location=device))\n",
    "gnn_model.eval()\n",
    "\n",
    "vit_model = ViTASL(num_classes).to(device)\n",
    "vit_model.load_state_dict(torch.load(\"models/asl_vit_model.pth\", map_location=device))\n",
    "vit_model.eval()\n",
    "\n",
    "# ========== Letter mapping (A-Z) ==========\n",
    "labels = [chr(ord('A') + i) for i in range(26)]\n",
    "\n",
    "# ========== Utility: Preprocessing ==========\n",
    "def preprocess(image):\n",
    "    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "    image = cv2.resize(image, (224, 224))\n",
    "    image = image.transpose((2, 0, 1))  # Channels-first\n",
    "    image = image.astype(np.float32) / 255.0\n",
    "    image = torch.tensor(image, dtype=torch.float).unsqueeze(0).to(device)\n",
    "    return image\n",
    "\n",
    "# ========== Real-time Camera Detection ==========\n",
    "cap = cv2.VideoCapture(0)\n",
    "while True:\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        break\n",
    "\n",
    "    img = preprocess(frame)\n",
    "\n",
    "    with torch.no_grad():\n",
    "        out_resnet = F.softmax(resnet_model(img), dim=1)\n",
    "        out_gnn = F.softmax(gnn_model(img), dim=1)\n",
    "        out_vit = F.softmax(vit_model(img), dim=1)\n",
    "\n",
    "        # Average ensemble\n",
    "        ensemble_out = (out_resnet + out_gnn + out_vit) / 3.0\n",
    "        pred_idx = torch.argmax(ensemble_out, dim=1).item()\n",
    "        pred_letter = labels[pred_idx]\n",
    "\n",
    "    # Display prediction on frame\n",
    "    cv2.putText(frame, f'ASL Pred: {pred_letter}', (30, 40),\n",
    "                cv2.FONT_HERSHEY_SIMPLEX, 1.2, (0, 255, 0), 3)\n",
    "    cv2.imshow(\"ASL Fingerspelling Detection\", frame)\n",
    "\n",
    "    # Quit on 'q' key\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
